### ISSUE TITLE
Support grammars with nesting

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/aoc-parse#2]
The puzzle input for [December 13, 2022](https://adventofcode.com/2022/day/13) looks like this:

```text
[1,1,3,1,1]
[1,1,5,1,1]

[[1],[2,3,4]]
[[1],4]

[9]
[[8,7,6]]
```

The lists can nest arbitrarily deep. aoc-parse needs new syntax to support this. Here's an attempt:

```rust
enum Value {
    Int(u32),
    List(Vec<Value>),
}

let value = parser!(
    rule value: Value = {
       n:u32 => Value::Int(n),
       "[]" => Value::List(vec![]),
       "[" vs:values "]" => Value::List(vs),
    };
    rule values: Vec<Value> = repeat_sep(value, ",");
    value
);

let p = parser!(sections(line(value) line(value)));
```

Ideally it would work without the type annotations, but that is probably impossible. I don't think Rust's type inference can handle it. In general, Rust makes you put types on things like `fn`s that might be mutually recursive.

**Comment by jorendorff** [comment]
The `value` parser above would compile to something like

```rust
let value = {
    let mut builder = ::aoc_parse::LetRecBuilder::new();
    let value: ::aoc_parse::RuleParser<Value> = builder.new_rule();
    let values: ::aoc_parse::RuleParser<Vec<Value>> = builder.new_rule();
    
    builder.assign_parser_for_rule(&value, parser!({
       n:u32 => Value::Int(n),
       "[]" => Value::List(vec![]),
       "[" vs:values "]" => Value::List(vs),
    });
    builder.assign_parser_for_rule(&values, parser!(repeat_sep(value, ",")));
    builder.build::<Value>(parser!(value))
);
```

and then some dire magic would be required to make it actually work at run time.

**Comment by AlisCode** [comment]
> Ideally it would work without the type annotations, but that is probably impossible. 

I tried doing that, and it doesn't seem possible indeed. 

* I've looked at returning an `impl Parser<Output = ...>` and ended up with an opaque type the compiler couldn't figure out
* I've looked at implementing a `BoxParser`, see if that would solve anything but didn't get very far (I didn't make enough time for that)

> I don't think Rust's type inference can handle it. In general, Rust makes you put types on things like fns that might be mutually recursive.

Very much so - that was what I was trying to do anyway.
Maybe there could be an `FnParser<F>` where `F: Fn(&str) -> Result< ... >`

I'd like to help more but I lack time these days, will keep following the issue though :)

**Comment by jorendorff** [comment]
Yes, I think some way of getting at `dyn` is a necessary first step. The typefulness of the core `Parser` and `ParseIter` traits makes this a nice challenge on its own. I'll work on it later.

> Maybe there could be an `FnParser<F>` where `F: Fn(&str) -> Result< ... >`

Not a bad idea.
